#!/bin/sh

# Create a symlink to this file in bin
# name it the name of the script to run (commitmeant)
# It will execute in the current directory, but with this projects pipenv
# 
# There is probably a better way, but this is how chatgpt told me to do it
original_directory=$(pwd)

# Find the actual location of the script
script_path="$0"
script_name=$(basename $script_path)
while [ -L "$script_path" ]; do
  script_path=$(readlink "$script_path")
done
script_directory=$(dirname "$(dirname "$(dirname "$script_path")")")

cd "$script_directory"
pipenv run python -c "
import os
import sys

os.chdir('$original_directory')
sys.path.insert(0, '$script_directory')

from src.cli.$script_name import main
main()
" "$@" 
# wow the #@ was figured out by copilot, GPT-4 never figured that out.
